name: Run test for sqlite
on: [push, pull_request]
jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Creating artifact to be tested
        run: |
          echo "Creating artifact"
          gcc -o db *.c 
      - name: Run tests
        run: |
          rspec
